name: gallery
description: A new Flutter application.
 
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  bloc: ^6.0.1
  equatable: ^1.2.3
  flutter_bloc: ^6.0.1
  image_picker: ^0.6.7+11
  cupertino_icons: ^1.0.0
  multi_masked_formatter: ^0.1.1
  google_fonts: ^1.1.0
  permission_handler: ^5.0.1+1

  firebase_storage: ^4.0.1
  firebase_core: "^0.5.0+1"
  firebase_auth: "^0.18.1+2"
  cloud_firestore: ^0.14.1+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/